import { getRandomImage } from './articleImages';

export interface Article {
    id: string;
    title: string;
    summary: string;
    image_url: string;
    category: 'holistic' | 'emotional' | 'functional' | 'orthomolecular' | 'energy' | 'herbal' | 'modern' | 'traditional' | 'nutrition' | 'mental' | 'detox' | 'lifestyle' | 'science';
    type: 'article' | 'video' | 'study' | 'podcast';
    views: number;
    featured: boolean;
    tags: string[];
    duration?: string;
    author: string;
    created_at: string;
    content?: string; // HTML content
    source?: string;
}

export const libraryCategories = [
    { id: 'all', name: 'الكل' },
    { id: 'holistic', name: 'الطب الشمولي' },
    { id: 'emotional', name: 'الطب الشعوري' },
    { id: 'functional', name: 'الطب الوظيفي' },
    { id: 'orthomolecular', name: 'الأورثوموليكولار' },
    { id: 'energy', name: 'الطب الطاقي' },
    { id: 'herbal', name: 'طب الأعشاب' },
    { id: 'modern', name: 'الطب الحديث' },
    { id: 'traditional', name: 'الطب التقليدي' },
];

const rawArticles: any[] = [
    // --- Holistic Medicine ---
    {
        id: 'holistic-1',
        title: 'الطب الشمولي: نظرة تتجاوز الأعراض',
        summary: 'كيف يربط الطب الشمولي بين الجسد والعقل والروح لعلاج جذور المرض بدلاً من تسكين الألم فقط.',
        image_url: getRandomImage('holistic'),
        category: 'holistic',
        type: 'article',
        views: 12500,
        featured: true,
        tags: ['شمولي', 'فلسفة', 'شفاء'],
        duration: '10 دقائق',
        author: 'د. عمر العماد',
        created_at: '2024-01-15',
        source: 'Mayo Clinic / Harvard Health'
    },
    {
        id: 'holistic-2',
        title: 'توازن الشاكرات والصحة الجسدية',
        summary: 'العلاقة العلمية والروحية بين مراكز الطاقة في الجسم وصحة الغدد الصماء.',
        image_url: 'https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=800&q=80',
        category: 'holistic',
        type: 'article',
        views: 8400,
        featured: false,
        tags: ['شاكرات', 'طاقة', 'غدد'],
        duration: '8 دقائق',
        author: 'د. سارة اليافعي',
        created_at: '2024-02-10',
        source: 'Journal of Holistic Nursing'
    },
    {
        id: 'holistic-3',
        title: 'الميكروبيوم: عقلك الثاني',
        summary: 'كيف تؤثر بكتيريا الأمعاء على قراراتك، مزاجك، وصحتك العامة بمفهوم الطب الشمولي.',
        image_url: 'https://images.unsplash.com/photo-1559757175-5700dde675bc?w=800&q=80',
        category: 'holistic',
        type: 'article',
        views: 15600,
        featured: true,
        tags: ['ميكروبيوم', 'أمعاء', 'عقل'],
        duration: '12 دقيقة',
        author: 'د. عمر العماد',
        created_at: '2024-03-05',
        source: 'Nature Microbiology'
    },
    {
        id: 'holistic-4',
        title: 'النوم والترميم الخلوي',
        summary: 'لماذا يحتاج جسدك للنوم العميق؟ عملية "الأوتوفاجي" وتنظيف السموم أثناء الليل.',
        image_url: 'https://images.unsplash.com/photo-1511295742362-92c96b50484f?w=800&q=80',
        category: 'holistic',
        type: 'video',
        views: 9200,
        featured: false,
        tags: ['نوم', 'تجدد', 'خلايا'],
        duration: '15:20 دقيقة',
        author: 'د. محمد الفايد',
        created_at: '2024-01-20',
        source: 'Sleep Foundation'
    },
    {
        id: 'holistic-5',
        title: 'التأريض (Earthing): العلاج بالأرض',
        summary: 'فوائد المشي حافياً على التراب وتأثيره على الالتهابات وتفريغ الشحنات الكهربائية.',
        image_url: 'https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?w=800&q=80',
        category: 'holistic',
        type: 'article',
        views: 7100,
        featured: false,
        tags: ['تأريض', 'طبيعة', 'التهابات'],
        duration: '6 دقائق',
        author: 'د. عمر العماد',
        created_at: '2024-04-12',
        source: 'Journal of Inflammation Research'
    },

    // --- Emotional Medicine ---
    {
        id: 'emotional-1',
        title: 'الخريطة الشعورية للأمراض',
        summary: 'كيف يتحول الحزن إلى ربو، والغضب إلى قرحة؟ فك شيفرة لغة الجسد.',
        image_url: getRandomImage('emotional'),
        category: 'emotional',
        type: 'article',
        views: 22000,
        featured: true,
        tags: ['نفسية', 'جسد', 'مشاعر'],
        duration: '14 دقيقة',
        author: 'لويز هاي (بتصرف د. عمر)',
        created_at: '2023-12-01',
        source: 'You Can Heal Your Life'
    },
    {
        id: 'emotional-2',
        title: 'الصدمات الموروثة',
        summary: 'هل ورثت قلق جدتك؟ علم الوراثة فوق الجينية (Epigenetics) وتأثير الصدمات العائلية.',
        image_url: 'https://images.unsplash.com/photo-1529333166437-7750a6dd5a70?w=800&q=80',
        category: 'emotional',
        type: 'video',
        views: 18500,
        featured: true,
        tags: ['وراثة', 'صدمات', 'عائلة'],
        duration: '20:00 دقيقة',
        author: 'مارك ولين',
        created_at: '2024-02-15',
        source: 'It Didn\'t Start with You'
    },
    {
        id: 'emotional-3',
        title: 'الغدة الدرقية والتعبير عن الذات',
        summary: 'لماذا تصاب النساء بمشاكل الدرقية أكثر؟ العلاقة بين "كبت الصوت" ومرض هاشيموتو.',
        image_url: 'https://images.unsplash.com/photo-1576091160550-217358c7db81?w=800&q=80',
        category: 'emotional',
        type: 'article',
        views: 11200,
        featured: false,
        tags: ['درقية', 'تعبير', 'حنجرة'],
        duration: '9 دقائق',
        author: 'د. كريستيان نورثوب',
        created_at: '2024-03-22',
        source: 'Women\'s Bodies, Women\'s Wisdom'
    },
    {
        id: 'emotional-4',
        title: 'القلب المكسور: حقيقة طبية',
        summary: 'متلازمة القلب المنكسر (Takotsubo) وكيف تؤثر الصدمات العاطفية فيزياءياً على عضلة القلب.',
        image_url: 'https://images.unsplash.com/photo-1516975080664-ed2fc6a32937?w=800&q=80',
        category: 'emotional',
        type: 'article',
        views: 9800,
        featured: false,
        tags: ['قلب', 'حزن', 'طب'],
        duration: '7 دقائق',
        author: 'د. جو ديسينزا',
        created_at: '2024-01-10',
        source: 'American Heart Association'
    },
    {
        id: 'emotional-5',
        title: 'تقنيات التحرر الشعوري (EFT)',
        summary: 'كيف تستخدم النقر (Tapping) لتحرير المسارات الطاقية ومعالجة الفوبيا والقلق.',
        image_url: getRandomImage('holistic'),
        category: 'emotional',
        type: 'video',
        views: 13400,
        featured: false,
        tags: ['EFT', 'نقر', 'قلق'],
        duration: '10:00 دقيقة',
        author: 'غاري كريغ',
        created_at: '2024-05-01',
        source: 'EFT International'
    },

    // --- Functional Medicine ---
    {
        id: 'functional-1',
        title: 'الالتهاب الخفي: القاتل الصامت',
        summary: 'لماذا يعتبر الالتهاب المزمن جذر معظم الأمراض الحديثة؟ وكيف نطفئه بالغذاء.',
        image_url: getRandomImage('functional'),
        category: 'functional',
        type: 'article',
        views: 19000,
        featured: true,
        tags: ['التهاب', 'مزمن', 'مناعة'],
        duration: '11 دقيقة',
        author: 'د. مارك هايمان',
        created_at: '2024-02-05',
        source: 'The UltraMind Solution'
    },
    {
        id: 'functional-2',
        title: 'ارتشاح الأمعاء (Leaky Gut)',
        summary: 'كيف يؤدي نفاذ جدار الأمعاء إلى أمراض المناعة الذاتية والحساسيات.',
        image_url: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800&q=80',
        category: 'functional',
        type: 'article',
        views: 14500,
        featured: true,
        tags: ['أمعاء', 'مناعة', 'جلوتين'],
        duration: '13 دقيقة',
        author: 'د. أليسيو فاسانو',
        created_at: '2024-03-15',
        source: 'Harvard Medical School'
    },
    {
        id: 'functional-3',
        title: 'مقاومة الأنسولين: بوابة الأمراض',
        summary: 'فهم جذور السكري من النوع الثاني، تكيس المبايض، والسمنة من منظور وظائف الأنسولين.',
        image_url: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=800&q=80',
        category: 'functional',
        type: 'video',
        views: 16200,
        featured: false,
        tags: ['أنسولين', 'سكري', 'سمنة'],
        duration: '18:30 دقيقة',
        author: 'د. جيسون فونغ',
        created_at: '2024-01-30',
        source: 'The Diabetes Code'
    },
    {
        id: 'functional-4',
        title: 'الغدة الكظرية وإرهاق القرن 21',
        summary: 'هل تعاني من التعب المستمر؟ تعرف على "Adrenal Fatigue" وكيفية استعادة نشاطك.',
        image_url: 'https://images.unsplash.com/photo-1447452001602-7090c7746361?w=800&q=80',
        category: 'functional',
        type: 'article',
        views: 10100,
        featured: false,
        tags: ['إرهاق', 'كورتيزول', 'طاقة'],
        duration: '8 دقائق',
        author: 'د. جيمس ويلسون',
        created_at: '2024-04-05',
        source: 'Adrenal Fatigue: The 21st Century Stress Syndrome'
    },
    {
        id: 'functional-5',
        title: 'السموم البيئية والهرمونات',
        summary: 'تأثير البلاستيك (BPA)، المبيدات، والمعادن الثقيلة على توازنك الهرموني.',
        image_url: 'https://images.unsplash.com/photo-1616790937107-1b4e545464c2?w=800&q=80',
        category: 'functional',
        type: 'article',
        views: 7800,
        featured: false,
        tags: ['سموم', 'هرمونات', 'بيئة'],
        duration: '10 دقائق',
        author: 'د. لارا بريدن',
        created_at: '2024-05-10',
        source: 'Period Repair Manual'
    },

    // --- Orthomolecular Medicine (Vitamins) ---
    {
        id: 'ortho-1',
        title: 'فيتامين C بجرعات عالية',
        summary: 'بروتوكولات د. لينوس بولينج لعلاج العدوى ودعم المناعة بجرعات ميجا من فيتامين C.',
        image_url: getRandomImage('orthomolecular'),
        category: 'orthomolecular',
        type: 'article',
        views: 20500,
        featured: true,
        tags: ['فيتامين C', 'مناعة', 'سرطان'],
        duration: '12 دقيقة',
        author: 'د. توماس ليفي',
        created_at: '2024-02-20',
        source: 'Primal Panacea'
    },
    {
        id: 'ortho-2',
        title: 'المغنيسيوم: المعدن المفقود',
        summary: 'لماذا يعاني 80% من الناس من نقص المغنيسيوم؟ وعلاقته بالقلق، العضلات، والقلب.',
        image_url: 'https://images.unsplash.com/photo-1596701399672-880556f89078?w=800&q=80',
        category: 'orthomolecular',
        type: 'article',
        views: 17800,
        featured: true,
        tags: ['مغنيسيوم', 'قلب', 'نفسية'],
        duration: '9 دقائق',
        author: 'د. كارولين دين',
        created_at: '2024-03-10',
        source: 'The Magnesium Miracle'
    },
    {
        id: 'ortho-3',
        title: 'فيتامين D3 ليس فيتامين!',
        summary: 'إنه هرمون ستيرويدي. لماذا الجرعات الرسمية غير كافية؟ وأهمية K2 معه.',
        image_url: 'https://images.unsplash.com/photo-1524250502761-1ac6f2e30d43?w=800&q=80',
        category: 'orthomolecular',
        type: 'video',
        views: 25000,
        featured: false,
        tags: ['فيتامين D', 'مناعة', 'عظام'],
        duration: '14:00 دقيقة',
        author: 'د. مايكل هوليك',
        created_at: '2024-01-05',
        source: 'The Vitamin D Solution'
    },
    {
        id: 'ortho-4',
        title: 'اليود: سر الذكاء والأيض',
        summary: 'هل الملح المدعم يكفي؟ بروتوكول اليود، السيلينيوم، وعلاقتهم بالثدي والبروستاتا.',
        image_url: 'https://images.unsplash.com/photo-1615485499973-513cc8d76db8?w=800&q=80',
        category: 'orthomolecular',
        type: 'article',
        views: 8900,
        featured: false,
        tags: ['يود', 'درقية', 'ذكاء'],
        duration: '11 دقيقة',
        author: 'د. ديفيد براونشتاين',
        created_at: '2024-04-15',
        source: 'Iodine: Why You Need It'
    },
    {
        id: 'ortho-5',
        title: 'مجموعة B المعقدة وال methylation',
        summary: 'جين MTHFR الشائع، ولماذا يحتاج البعض صيغ "ميثيل" خاصة من الفيتامينات.',
        image_url: 'https://images.unsplash.com/photo-1579684453423-f84349ca60df?w=800&q=80',
        category: 'orthomolecular',
        type: 'article',
        views: 6500,
        featured: false,
        tags: ['جينات', 'فيتامين B', 'أعصاب'],
        duration: '10 دقائق',
        author: 'د. بن لينش',
        created_at: '2024-05-20',
        source: 'Dirty Genes'
    },

    // --- Energy Medicine ---
    {
        id: 'energy-1',
        title: 'الشفاء بالترددات (Rife)',
        summary: 'تاريخ تقنية رويال رايف في تدمير مسببات الأمراض بالرنين، وحقائق علمية.',
        image_url: getRandomImage('energy'),
        category: 'energy',
        type: 'article',
        views: 11500,
        featured: true,
        tags: ['ترددات', 'رايف', 'رنين'],
        duration: '15 دقيقة',
        author: 'د. نيناد ستويانوفيتش',
        created_at: '2024-02-25',
        source: 'The Rife Handbook'
    },
    {
        id: 'energy-2',
        title: 'القلب: أقوى مجال كهرومغناطيسي',
        summary: 'قلبك يرسل إيماضات تؤثر على من حولك. علم معهد HeartMath وتناسق القلب والدماغ.',
        image_url: 'https://images.unsplash.com/photo-1505567745926-ba89000d255a?w=800&q=80',
        category: 'energy',
        type: 'video',
        views: 13200,
        featured: true,
        tags: ['قلب', 'طاقة', 'تخاطر'],
        duration: '12:45 دقيقة',
        author: 'معهد HeartMath',
        created_at: '2024-03-30',
        source: 'HeartMath Institute Research'
    },
    {
        id: 'energy-3',
        title: 'الوخز بالإبر ومسارات الطاقة',
        summary: 'كيف تتدفق "الكي" (Qi) عبر مسارات الجسم؟ نظرة في الطب الصيني الطاقي.',
        image_url: getRandomImage('holistic'),
        category: 'energy',
        type: 'article',
        views: 7400,
        featured: false,
        tags: ['إبر صينية', 'طاقة', 'ألم'],
        duration: '8 دقائق',
        author: 'د. دانيال كيوان',
        created_at: '2024-01-25',
        source: 'The Spark in the Machine'
    },
    {
        id: 'energy-4',
        title: 'البيندوليوم (Rhabdomancy) وعلم الرنين',
        summary: 'استخدام البندول في التشخيص الطاقي واختبار توافق الأغذية والأدوية.',
        image_url: 'https://images.unsplash.com/photo-1515238152791-8216bfdf89a7?w=800&q=80',
        category: 'energy',
        type: 'article',
        views: 5600,
        featured: false,
        tags: ['بندول', 'تشخيص', 'طاقة'],
        duration: '7 دقائق',
        author: 'كريم إبراهيم',
        created_at: '2024-04-20',
        source: 'BioGeometry'
    },
    {
        id: 'energy-5',
        title: 'الماء وذاكرة الحياة',
        summary: 'أبحاث ماسارو إيموتو: كيف تؤثر الكلمات والمشاعر والطاقة على بلورات الماء في جسدك.',
        image_url: 'https://images.unsplash.com/photo-1548839140-29a749e1cf4d?w=800&q=80',
        category: 'energy',
        type: 'video',
        views: 19800,
        featured: false,
        tags: ['ماء', 'ذاكرة', 'نية'],
        duration: '08:20 دقيقة',
        author: 'ماسارو إيموتو',
        created_at: '2024-05-05',
        source: 'The Hidden Messages in Water'
    },

    // --- Herbal Medicine ---
    {
        id: 'herbal-1',
        title: 'الأشواجاندا: عشبة التوازن',
        summary: 'كيف تساعدك هذه العشبة التكيفية (Adaptogen) على مقاومة التوتر وتحسين النوم.',
        image_url: getRandomImage('herbal'),
        category: 'herbal',
        type: 'article',
        views: 10500,
        featured: true,
        tags: ['أعشاب', 'توتر', 'هرمونات'],
        duration: '6 دقائق',
        author: 'د. أندرو ويل',
        created_at: '2024-02-12',
        source: 'Integrative Medicine'
    },
    {
        id: 'herbal-2',
        title: 'الكركم (Curcumin): مضاد الالتهاب الذهبي',
        summary: 'الفرق بين الكركم والكركمين، وكيفية زيادة امتصاصه 2000% باستخدام الفلفل الأسود والدهون.',
        image_url: 'https://images.unsplash.com/photo-1615485290382-441e4d049cb5?w=800&q=80',
        category: 'herbal',
        type: 'article',
        views: 12100,
        featured: false,
        tags: ['كركم', 'التهاب', 'مفاصل'],
        duration: '7 دقائق',
        author: 'د. مايكل جرير',
        created_at: '2024-03-18',
        source: 'NutritionFacts.org'
    },
    {
        id: 'herbal-3',
        title: 'الفطر الريشي (Reishi): إكسير الخلود',
        summary: 'فوائد الفطر الطبي لدعم المناعة، مكافحة السرطان، وتهدئة الجهاز العصبي.',
        image_url: 'https://images.unsplash.com/photo-1604608670838-842232a5146c?w=800&q=80',
        category: 'herbal',
        type: 'article',
        views: 6300,
        featured: false,
        tags: ['فطر', 'مناعة', 'خلود'],
        duration: '8 دقائق',
        author: 'بول ستامتس',
        created_at: '2024-01-15',
        source: 'Mycelium Running'
    },
    {
        id: 'herbal-4',
        title: 'زيت الزعتر البري (Oregano Oil)',
        summary: 'أقوى مضاد حيوي طبيعي؟ استخدامه للفطريات (الكانديدا)، البكتيريا، والفيروسات.',
        image_url: 'https://images.unsplash.com/photo-1599305445671-ac291c95aaa9?w=800&q=80',
        category: 'herbal',
        type: 'article',
        views: 8700,
        featured: false,
        tags: ['مضاد حيوي', 'فطريات', 'زعتر'],
        duration: '6 دقائق',
        author: 'د. جوش آكس',
        created_at: '2024-04-25',
        source: 'Ancient Remedies'
    },
    {
        id: 'herbal-5',
        title: 'حليب الشوك (Milk Thistle) والكبد',
        summary: 'كيف تحمي عشبة السيليمارين الكبد من السموم وتساعد في تجديد خلاياه.',
        image_url: 'https://images.unsplash.com/photo-1530910606992-0b2dd8c3f7d8?w=800&q=80',
        category: 'herbal',
        type: 'article',
        views: 5900,
        featured: false,
        tags: ['كبد', 'ديتوكس', 'أعشاب'],
        duration: '5 دقائق',
        author: 'د. ساندرا كابوت',
        created_at: '2024-05-15',
        source: 'The Liver Cleansing Diet'
    },

    // --- Modern Medicine (Critical View) ---
    {
        id: 'modern-1',
        title: 'الطب الشخصي (Precision Medicine)',
        summary: 'مستقبل الطب: علاج يفصل حسب جيناتك وبصمتك البيولوجية وليس "مقاس واحد للجميع".',
        image_url: getRandomImage('modern'),
        category: 'modern',
        type: 'article',
        views: 9200,
        featured: true,
        tags: ['جينات', 'مستقبل', 'تكنولوجيا'],
        duration: '9 دقائق',
        author: 'د. ليروي هود',
        created_at: '2024-02-28',
        source: 'The Age of Scientific Wellness'
    },
    {
        id: 'modern-2',
        title: 'المضادات الحيوية: سلاح ذو حدين',
        summary: 'متى تنقذ الحياة ومتى تدمر المناعة؟ وكيف تحمي أمعاءك أثناء الكورس العلاجي.',
        image_url: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=800&q=80',
        category: 'modern',
        type: 'article',
        views: 11000,
        featured: false,
        tags: ['مناعة', 'بكتيريا', 'أدوية'],
        duration: '8 دقائق',
        author: 'د. مارتن بليزر',
        created_at: '2024-03-12',
        source: 'Missing Microbes'
    },
    {
        id: 'modern-3',
        title: 'العلاج بالخلايا الجذعية',
        summary: 'ثورة تجديد الأنسجة: من علاج المفاصل المتآكلة إلى محاربة الشيخوخة.',
        image_url: 'https://images.unsplash.com/photo-1530210124550-912dc1381cb8?w=800&q=80',
        category: 'modern',
        type: 'video',
        views: 14500,
        featured: false,
        tags: ['خلايا جذعية', 'تجديد', 'مستقبل'],
        duration: '11:15 دقيقة',
        author: 'د. نيل ريوردان',
        created_at: '2024-01-18',
        source: 'Stem Cell Therapy: A Rising Tide'
    },

    // --- Traditional Medicine ---
    {
        id: 'traditional-1',
        title: 'الحجامة: بين السنة والعلم',
        summary: 'آلية عمل الحجامة في تنشيط الدورة الدموية، إزالة الركد (Stagnation)، وتحفيز المناعة.',
        image_url: getRandomImage('traditional'),
        category: 'traditional',
        type: 'article',
        views: 16700,
        featured: true,
        tags: ['حجامة', 'سنة', 'دورة دموية'],
        duration: '10 دقائق',
        author: 'د. أحمد حفني',
        created_at: '2024-02-08',
        source: 'Traditional Islamic Medicine'
    },
    {
        id: 'traditional-2',
        title: 'الأيورفيدا: طب العناصر الخمسة',
        summary: 'اعرف نوع جسمك (Dosha): فاتا، بيتا، أم كافا؟ وكيف تأكل حسب طبيعتك.',
        image_url: 'https://images.unsplash.com/photo-1600618528240-fb9fc964b853?w=800&q=80',
        category: 'traditional',
        type: 'article',
        views: 8200,
        featured: false,
        tags: ['أيورفيدا', 'هند', 'طبيعة'],
        duration: '12 دقيقة',
        author: 'د. ديباك شوبرا',
        created_at: '2024-03-25',
        source: 'Perfect Health'
    },
    {
        id: 'traditional-3',
        title: 'الصمغ العربي واللبان',
        summary: 'كنوز الجزيرة العربية: فوائد الصمغ للكلى واللبان (Boswellia) للالتهابات.',
        image_url: 'https://images.unsplash.com/photo-1629196914375-f7e48f477b6d?w=800&q=80',
        category: 'traditional',
        type: 'article',
        views: 9600,
        featured: false,
        tags: ['أعشاب عربية', 'كلى', 'بخور'],
        duration: '7 دقائق',
        author: 'د. جميل القدسي',
        created_at: '2024-04-30',
        source: 'Arabian Herbal Medicine'
    }
];

export const localArticles: Article[] = rawArticles.map(article => ({
    ...article,
    image_url: getRandomImage(article.category)
}));
