/**
 * em-data.ts — الطب الشعوري Database
 * 30+ حالة مع الصراع الشعوري الجذر + بروتوكول الشفاء
 * مبني على: الطب النفسي الجسدي + الطب الجديد الألماني + لويز هاي + الأبحاث الحديثة
 */

import { EmotionalCondition } from './em-types';

export const EMOTIONAL_CONDITIONS: EmotionalCondition[] = [
    {
        id: 'headache',
        symptom: 'الصداع المزمن والشقيقة',
        targetOrgan: 'الدماغ / الأوعية الدموية الدماغية',
        organSystem: 'nervous',
        emotionalConflict: 'صراع داخلي بين ما تريده وما يُتوقع منك — ضغط لإرضاء الآخرين وإهمال الذات',
        biologicalPurpose: 'الجسم يُنبّهك أن توقفت عن الاستماع لنفسك. الألم هو إشارة لإعادة التوازن.',
        triggerEmotions: ['التوتر', 'الكمالية', 'الخوف من الفشل', 'الإرهاق العقلي'],
        affectedChakra: 'الشاكرا السادسة — العين الثالثة',
        healingSteps: [
            { step: 1, icon: '🧘', title: 'توقف وتنفّس', description: 'خمس دقائق تنفس عميق من البطن. أغمض عينيك وأرخِ فك اسنانك وكتفيك.', duration: '5 دقائق' },
            { step: 2, icon: '📝', title: 'تحديد الصراع', description: 'اسأل نفسك: ما الذي أحاول إرضاءه رغماً عني؟ ما القرار الذي أتأخر في اتخاذه؟', duration: '10 دقائق' },
            { step: 3, icon: '💬', title: 'الحوار الداخلي', description: 'قل بصوت عالٍ: "أمنح نفسي الإذن بأن أكون على خطأ. أسمح لنفسي بالراحة."', duration: '5 دقائق' },
            { step: 4, icon: '🌊', title: 'تمرين الضغط', description: 'ضع إبهامك على نقطة LI4 (بين إبهام السبابة) لمدة دقيقة. يخفف الصداع فوراً.', duration: '3 دقائق' },
            { step: 5, icon: '🌿', title: 'إعادة البرمجة', description: 'اكتب ثلاثة قرارات تريد اتخاذها لنفسك دون الاعتماد على موافقة الآخرين.', duration: '15 دقائق' },
        ],
        healingAffirmation: 'أنا في سلام مع تدفق الحياة. أفكاري ناعمة ومحبة. أنا آمن.',
        affirmationEn: 'I release all tension. I am at peace with the flow of life.',
        breathingTech: '4-7-8',
        severity: 'moderate',
        prevalence: 9,
        color: '#7C3AED',
    },
    {
        id: 'back-pain',
        symptom: 'ألم أسفل الظهر',
        targetOrgan: 'العمود الفقري القطني / العضلات المحيطة',
        organSystem: 'musculo',
        emotionalConflict: 'شعور بالعبء الزائد — تحمّل مسؤوليات أكثر مما تستطيع، أو خوف من الفقر وانعدام الدعم',
        biologicalPurpose: 'الظهر هو ركيزة جسمك. ألمه يعني أنك تحتاج دعماً لا تطلبه.',
        triggerEmotions: ['الخوف المالي', 'الإرهاق', 'عدم الشعور بالدعم', 'الإحساس بالوحدة'],
        healingSteps: [
            { step: 1, icon: '🤲', title: 'طلب المساعدة', description: 'تدرّب اليوم على طلب المساعدة في شيء واحد صغير. الضعف ليس عيباً.', duration: 'يومياً' },
            { step: 2, icon: '🧘', title: 'تمرين الجذر', description: 'اجلس على الأرض. ضع يديك على الأرض. تخيل جذوراً تمتد من جسمك للأرض. أنت مدعوم.', duration: '10 دقائق' },
            { step: 3, icon: '💰', title: 'مواجهة قلق المال', description: 'اكتب ثلاثة موارد لديك الآن — ليس المال فقط. الوقت، المعرفة، العلاقات.', duration: '10 دقائق' },
            { step: 4, icon: '🏃', title: 'التحرك', description: 'مشي ١٥ دقيقة يومياً. الحركة تُرسل إشارة للجسم: أنا قادر، أنا بخير.', duration: '15 دقائق' },
            { step: 5, icon: '✨', title: 'التأكيد الشفائي', description: 'ردد التأكيد مع وضع يدك على أسفل ظهرك بحنان.', duration: '5 دقائق' },
        ],
        healingAffirmation: 'الكون يدعمني دائماً. أثق في تدفق الحياة وأستقبل فضلها بامتنان.',
        affirmationEn: 'I trust life to support me. I am safe and secure.',
        breathingTech: 'box',
        severity: 'moderate',
        prevalence: 10,
        color: '#059669',
    },
    {
        id: 'ibs',
        symptom: 'القولون العصبي والاضطرابات الهضمية',
        targetOrgan: 'الأمعاء الغليظة والدقيقة',
        organSystem: 'digestive',
        emotionalConflict: 'صعوبة "هضم" مواقف الحياة أو تجارب مؤلمة — التشبث بما يجب إطلاقه',
        biologicalPurpose: 'الأمعاء تعكس قدرتك على استيعاب الجديد والتخلص من القديم.',
        triggerEmotions: ['القلق', 'الخوف من الجديد', 'التشبث', 'الغضب المكبوت'],
        affectedChakra: 'الشاكرا الثالثة — قوة الإرادة',
        healingSteps: [
            { step: 1, icon: '🌊', title: 'تنفس البطن', description: '١٠ دقائق تنفس عميق يصل للبطن. يُهدئ الجهاز العصبي اللاإرادي المحيط بالقولون.', duration: '10 دقائق' },
            { step: 2, icon: '📓', title: 'يوميات التفريغ', description: 'اكتب ما تحمله ولا تستطيع قوله. ثم أتلف الورقة كرمز للإطلاق.', duration: '20 دقائق' },
            { step: 3, icon: '🍵', title: 'الدعم الغذائي', description: 'النعناع، الكمون، والشمر تُهدئ الالتهاب. تجنب السكريات المُصنّعة أسبوعاً.', duration: 'أسبوع' },
            { step: 4, icon: '🔄', title: 'تمرين الإطلاق', description: 'فكّر في موقف تتشبث به. تخيله كشيء في يدك. وببطء — افتح يدك ودعه يطير.', duration: '10 دقائق' },
            { step: 5, icon: '✨', title: 'تأكيد شفائي', description: 'الحياة تُدبّر لي دائماً. أطلق القديم بسهولة وأستقبل الجديد بفرح.', duration: '5 دقائق' },
        ],
        healingAffirmation: 'أهضم الحياة بسهولة وسلام. أطلق ما لا يخدمني وأستقبل الخير.',
        affirmationEn: 'I digest life with ease. I release what no longer serves me.',
        breathingTech: 'coherence',
        severity: 'moderate',
        prevalence: 8,
        color: '#EA580C',
    },
    {
        id: 'hypertension',
        symptom: 'ارتفاع ضغط الدم',
        targetOrgan: 'الشرايين والقلب',
        organSystem: 'cardiac',
        emotionalConflict: 'ضغط داخلي للسيطرة على كل شيء — الخوف من فقدان التحكم أو الاندفاع العاطفي المكبوت',
        biologicalPurpose: 'الجسم يرفع الضغط استعداداً للدفاع — صراع بيولوجي قديم.',
        triggerEmotions: ['الحاجة للسيطرة', 'الغضب المكبوت', 'الخوف المزمن', 'الكمالية'],
        healingSteps: [
            { step: 1, icon: '❤️', title: 'قياس عاطفي', description: 'اسأل نفسك: ما الذي لا أستطيع التحكم فيه ويخيفني؟ اكتبه بصراحة.', duration: '10 دقائق' },
            { step: 2, icon: '🌬️', title: 'تنفس 4-7-8', description: 'شهيق 4 ثوان، احبس 7، زفير 8. يُنشّط الجهاز البرا سمبثاوي ويخفض الضغط فوراً.', duration: '10 دقائق' },
            { step: 3, icon: '🚿', title: 'المشي في الطبيعة', description: '30 دقيقة مشي في مكان هادئ. يُخفض الكورتيزول والأدرينالين بشكل مباشر.', duration: '30 دقائق' },
            { step: 4, icon: '💬', title: 'إفراغ الغضب', description: 'اكتب رسالة لشخص أو موقف تشعر بالغضب منه. لا ترسلها. فقط اكتبها.', duration: '20 دقائق' },
            { step: 5, icon: '🕊️', title: 'تسليم الأمور', description: 'ممارسة التسليم اليومي: "أفعل ما بوسعي، وأسلّم بقية الأمور."', duration: 'يومياً' },
        ],
        healingAffirmation: 'أنا آمن. أثق في الحياة. أسمح لنفسي بالانسياب الهادئ مع التدفق.',
        affirmationEn: 'I release control. Life is safe and I flow with ease.',
        breathingTech: '4-7-8',
        severity: 'severe',
        prevalence: 9,
        color: '#E11D48',
    },
    {
        id: 'thyroid',
        symptom: 'اضطرابات الغدة الدرقية',
        targetOrgan: 'الغدة الدرقية',
        organSystem: 'endocrine',
        emotionalConflict: 'شعور بأنك لا تستطيع فعل ما تريد — القيود والتعبير المكبوت عن النفس',
        biologicalPurpose: 'الغدة الدرقية تتحكم في إيقاع الجسم — كبتها يعني كبت إيقاعك الحقيقي.',
        triggerEmotions: ['الشعور بالحصار', 'كبت التعبير', 'الإحساس بالعجز', 'الإحباط المزمن'],
        affectedChakra: 'الشاكرا الخامسة — التعبير والإبداع',
        healingSteps: [
            { step: 1, icon: '🎵', title: 'التعبير الصوتي', description: 'الغناء ولو بمفردك. التعبير الصوتي يُنشّط الغدة الدرقية مباشرة.', duration: '10 دقائق' },
            { step: 2, icon: '✍️', title: 'الكتابة الإبداعية', description: 'اكتب ما تريد قوله للعالم ولا تجرؤ عليه. كل يوم فقرة.', duration: '15 دقائق' },
            { step: 3, icon: '🧘', title: 'تأمل الحلق', description: 'ركز على منطقة حلقك أثناء التأمل. تخيل ضوءاً أزرق يشع منها.', duration: '10 دقائق' },
            { step: 4, icon: '💪', title: 'تحديد حدود', description: 'هذا الأسبوع، قل "لا" لطلب واحد لا تريد الاستجابة له.', duration: 'أسبوع' },
            { step: 5, icon: '✨', title: 'تأكيد شفائي', description: 'رددها أمام المرآة: "يحق لي التعبير عن نفسي بحرية وفرح."', duration: '5 دقائق' },
        ],
        healingAffirmation: 'يحق لي التعبير الحر. أقول الحقيقة بمحبة وأعيش بأصالة.',
        affirmationEn: 'I express myself freely and joyfully. I am free to be me.',
        breathingTech: 'lions',
        severity: 'moderate',
        prevalence: 7,
        color: '#9333EA',
    },
    {
        id: 'skin-eczema',
        symptom: 'الإكزيما والأمراض الجلدية',
        targetOrgan: 'الجلد',
        organSystem: 'skin',
        emotionalConflict: 'الرغبة في التعبير عمّا بداخلك مع الخوف من ما سيراه الآخرون — الهشاشة المخفية',
        biologicalPurpose: 'الجلد هو حدودك مع العالم — التهابه يعني صراعاً في حدود هويتك.',
        triggerEmotions: ['الحساسية المفرطة', 'الشعور بالانتقاد', 'الخوف من الظهور', 'الرفض المتوقع'],
        healingSteps: [
            { step: 1, icon: '🪞', title: 'تمرين المرآة', description: 'انظر لنفسك في المرآة وقل بحنان: "أنت جميل كما أنت. أحبك."', duration: '5 دقائق' },
            { step: 2, icon: '🛀', title: 'العناية بالجلد كطقس', description: 'ضع المرطب على جلدك ببطء وانتباه كاملين. اشعر أنك تُغذي نفسك بالمحبة.', duration: '10 دقائق' },
            { step: 3, icon: '💬', title: 'حد مع الانتقاد', description: 'لاحظ الصوت الداخلي الناقد. قل له: "شكراً لحرصك، لكن لا أحتاجك الآن."', duration: 'يومياً' },
            { step: 4, icon: '🌿', title: 'تغذية مضادة للالتهاب', description: 'أضف زيت الكتان، الكركم، والزنك لنظامك الغذائي.', duration: 'شهر' },
            { step: 5, icon: '✨', title: 'تأكيد شفائي', description: 'جلدي رقيق وجميل. أشعر بالأمان بداخلي وأبدو جميلاً بالخارج.', duration: '5 دقائق' },
        ],
        healingAffirmation: 'أنا آمن في جلدي. أحب نفسي وأرضى عنها. العالم آمن ومحب.',
        affirmationEn: 'I am safe in my own skin. I love and accept myself completely.',
        breathingTech: '4-7-8',
        severity: 'mild',
        prevalence: 7,
        color: '#D97706',
    },
    {
        id: 'asthma',
        symptom: 'الربو وضيق التنفس',
        targetOrgan: 'الرئتين والشعب الهوائية',
        organSystem: 'respiratory',
        emotionalConflict: 'شعور بالاختناق في بيئة أو علاقة — صعوبة "أخذ المساحة" في الحياة',
        biologicalPurpose: 'التنفس هو الحياة — صعوبته تعني صعوبة في الشعور بحق الوجود والمساحة.',
        triggerEmotions: ['الشعور بالاختناق', 'القمع', 'الخوف من المستقبل', 'البيئة الضاغطة'],
        healingSteps: [
            { step: 1, icon: '🌬️', title: 'تدريب التنفس', description: 'تنفس Buteyko يُوسّع قدرة الرئتين. خمس دقائق صباحاً ومساءً.', duration: '5 دقائق' },
            { step: 2, icon: '🏠', title: 'تقييم البيئة', description: 'هل مكانك الحالي (بيت، عمل، علاقة) يجعلك تشعر بالاختناق؟ كن صريحاً.', duration: '15 دقائق' },
            { step: 3, icon: '🚀', title: 'توسيع المساحة', description: 'افعل شيئاً واحداً هذا الأسبوع يُشعرك أنك تأخذ مساحتك: درس، هواية، قرار.', duration: 'أسبوع' },
            { step: 4, icon: '🌲', title: 'الطبيعة والهواء النقي', description: '20 دقيقة يومياً في مكان مفتوح. الرئتان تشفيان في الهواء الطلق.', duration: '20 دقائق' },
            { step: 5, icon: '✨', title: 'تأكيد شفائي', description: 'للحياة مساحة وفيرة بالنسبة لي. أتنفس بسهولة وحرية وأمتلئ بالحياة.', duration: '5 دقائق' },
        ],
        healingAffirmation: 'أتنفس عميقاً وبحرية. الحياة مساحة واسعة وأنا في أمان بها.',
        affirmationEn: 'I breathe freely and deeply. Life supports me fully.',
        breathingTech: 'buteyko',
        severity: 'severe',
        prevalence: 7,
        color: '#0891B2',
    },
    {
        id: 'neck-pain',
        symptom: 'ألم الرقبة والكتفين',
        targetOrgan: 'عضلات العنق والرقبة',
        organSystem: 'musculo',
        emotionalConflict: 'حمل مسؤوليات الآخرين على كتفيك — رؤية المواقف من زاوية واحدة فقط',
        biologicalPurpose: 'الرقبة تُمكّنك من الرؤية في كل الاتجاهات — تصلبها يعني تصلب الرأي.',
        triggerEmotions: ['العناد', 'رفض المرونة', 'الإفراط في تحمل المسؤولية', 'الرؤية الأحادية'],
        healingSteps: [
            { step: 1, icon: '🔄', title: 'تمرين التدوير', description: 'دوّر رقبتك ببطء شديد يمين ويسار. مع كل دوران قل: "أنا منفتح لرؤية المواقف بشكل جديد."', duration: '5 دقائق' },
            { step: 2, icon: '🤔', title: 'تحدي زاوية النظر', description: 'خذ موقفاً يزعجك الآن واسأل: كيف قد يكون لهذا الشخص وجهة نظر منطقية؟', duration: '10 دقائق' },
            { step: 3, icon: '🧖', title: 'تدليك الكتفين', description: 'دلّك نقطة GB21 (أعلى الكتف) ببطء. يُطلق التوتر المتراكم.', duration: '5 دقائق' },
            { step: 4, icon: '🛑', title: 'تفويض مهمة', description: 'اليوم، فوّض مهمة واحدة لشخص آخر. ليس لأنك عاجز، بل لأنك تثق.', duration: 'يومياً' },
            { step: 5, icon: '✨', title: 'تأكيد شفائي', description: 'أنا مرن في تفكيري وقلبي. أسمح للحياة بأن تُعلّمني من زوايا متعددة.', duration: '5 دقائق' },
        ],
        healingAffirmation: 'أنا مرن ومنفتح. أستطيع رؤية وجهات نظر متعددة بسهولة ومحبة.',
        affirmationEn: 'I am flexible and open. I see all sides with ease and love.',
        breathingTech: 'box',
        severity: 'mild',
        prevalence: 9,
        color: '#059669',
    },
    {
        id: 'insomnia',
        symptom: 'الأرق وصعوبة النوم',
        targetOrgan: 'الجهاز العصبي / الدماغ',
        organSystem: 'nervous',
        emotionalConflict: 'دوّامة الأفكار — عدم القدرة على "ترك" اليوم ومشاكله قبل النوم',
        biologicalPurpose: 'النوم هو الإطلاق اليومي. رفضه يعني رفض الاستسلام الجميل.',
        triggerEmotions: ['القلق', 'فرط التفكير', 'الخوف من الغد', 'الشعور بعدم الإنجاز'],
        healingSteps: [
            { step: 1, icon: '🌙', title: 'طقس النوم', description: '30 دقيقة قبل النوم: لا شاشات. شمعة أو إضاءة دافئة. كوب شاي أعشاب.', duration: '30 دقائق' },
            { step: 2, icon: '✍️', title: 'تفريغ الذهن', description: 'اكتب كل ما يدور في رأسك على ورقة. الكتابة تُنقل القلق من العقل للورق.', duration: '10 دقائق' },
            { step: 3, icon: '🙏', title: 'تأمل الامتنان', description: 'ثلاثة أشياء جميلة حدثت اليوم ولو صغيرة. هذا يُنشّط الجهاز البرا سيمبثاوي.', duration: '5 دقائق' },
            { step: 4, icon: '🌬️', title: 'تنفس 4-7-8', description: 'الأكثر فاعلية للنوم. كرره ٤ مرات. ترياق طبيعي مثبت علمياً.', duration: '5 دقائق' },
            { step: 5, icon: '✨', title: 'إطلاق اليوم', description: 'قل: "أسلّم هذا اليوم. فعلت ما في وسعي. الليل للراحة والشكر."', duration: '2 دقيقة' },
        ],
        healingAffirmation: 'أُطلق يومي بامتنان وأستسلم لراحة النوم العميقة بأمان.',
        affirmationEn: 'I release my day with gratitude and surrender to peaceful sleep.',
        breathingTech: '4-7-8',
        severity: 'moderate',
        prevalence: 8,
        color: '#4F46E5',
    },
    {
        id: 'chronic-fatigue',
        symptom: 'الإرهاق المزمن ونقص الطاقة',
        targetOrgan: 'الغدة الكظرية / الخلايا',
        organSystem: 'endocrine',
        emotionalConflict: 'استنزاف الطاقة في ما لا يُغذيك — حياة لا تتوافق مع قيمك الحقيقية',
        biologicalPurpose: 'الإرهاق هو رسالة جسمك: "هذا المسار لا يُغذيني، أحتاج التوقف والإعادة."',
        triggerEmotions: ['فقدان المعنى', 'الإفراط في العطاء', 'إهمال الذات', 'الشعور بانعدام القيمة'],
        healingSteps: [
            { step: 1, icon: '🔋', title: 'تقييم الطاقة', description: 'اكتب عشرة أشياء في حياتك. ضع "+" بجانب ما يمنحك طاقة، "-" بجانب ما يستنزفها.', duration: '15 دقائق' },
            { step: 2, icon: '🚫', title: 'الحد الذهبي', description: 'قلّص نشاطاً واحداً مستنزفاً هذا الأسبوع بـ١٠٪ فقط. لا حاجة لثورة.', duration: 'أسبوع' },
            { step: 3, icon: '🌱', title: 'نشاط يُغذيك', description: 'أضف ١٥ دقيقة يومية لشيء تحبه حقاً. ليس لأنه مفيد، بل لأنه يُسعدك.', duration: 'يومياً' },
            { step: 4, icon: '☀️', title: 'الشمس والنوم', description: '١٠ دقائق شمس صباحية تُصلح الساعة البيولوجية وترفع مستوى الكورتيزول الصحي.', duration: '10 دقائق' },
            { step: 5, icon: '✨', title: 'تأكيد شفائي', description: 'طاقتي تتجدد باستمرار. أُعطي بفرح وأستقبل بامتنان. أنا يستحق الراحة.', duration: '5 دقائق' },
        ],
        healingAffirmation: 'طاقتي الحيوية تتجدد. أمنح بفرح وأُعيد شحن نفسي بمحبة.',
        affirmationEn: 'My energy renews with ease. I give joyfully and receive gratefully.',
        breathingTech: 'coherence',
        severity: 'moderate',
        prevalence: 8,
        color: '#9333EA',
    },
    {
        id: 'heart-palpitation',
        symptom: 'خفقان القلب والقلق',
        targetOrgan: 'القلب / الجهاز العصبي اللاإرادي',
        organSystem: 'cardiac',
        emotionalConflict: 'الخوف من المستقبل أو من فقدان شيء مهم — الحاجة الماسّة للأمان',
        biologicalPurpose: 'القلب يُسرّع ليُعدّك للمواجهة — لكن في حالة الخوف المزمن يصبح إجهاداً.',
        triggerEmotions: ['الخوف', 'القلق المزمن', 'الهلع', 'عدم اليقين'],
        healingSteps: [
            { step: 1, icon: '❤️', title: 'وضع يد القلب', description: 'ضع يدك على قلبك بحنان. قل: "أنا هنا. أنت بأمان. كل شيء على ما يرام."', duration: '3 دقائق' },
            { step: 2, icon: '🌬️', title: 'تنفس القلب (HeartMath)', description: 'تنفس بتمهل من منطقة القلب. ١٠ مرات. يُهدئ الجهاز العصبي فوراً.', duration: '5 دقائق' },
            { step: 3, icon: '🧠', title: 'تحديد الخوف', description: 'اكتب الخوف الذي بداخلك بوضوح. السؤال الأسوأ الذي تخشاه. ثم تعامل معه.', duration: '15 دقائق' },
            { step: 4, icon: '🌈', title: 'بناء الأمان الداخلي', description: 'تذكر ثلاث مواقف تغلبت فيها على الخوف. أنت أقوى مما تظن.', duration: '10 دقائق' },
            { step: 5, icon: '✨', title: 'تأكيد شفائي', description: 'قلبي آمن وسليم. أثق في قدرتي على التعامل مع الحياة. أنا في أمان دائماً.', duration: '5 دقائق' },
        ],
        healingAffirmation: 'قلبي يدق بنعومة واطمئنان. أنا آمن في هذه اللحظة وفي كل لحظة.',
        affirmationEn: 'My heart beats with ease and peace. I am safe in this moment.',
        breathingTech: 'heartmath',
        severity: 'severe',
        prevalence: 8,
        color: '#E11D48',
    },
    {
        id: 'bladder-issues',
        symptom: 'اضطرابات المثانة والتبول',
        targetOrgan: 'المثانة / الجهاز البولي',
        organSystem: 'urinary',
        emotionalConflict: 'القلق الشديد والتوتر المتراكم — الإحساس بالتهديد أو الضغط المستمر',
        biologicalPurpose: 'المثانة تُخزّن وتُطلق — اختلالها يعكس صعوبة إطلاق القلق.',
        triggerEmotions: ['القلق', 'الخوف', 'التهديد المزمن', 'التوتر الاجتماعي'],
        healingSteps: [
            { step: 1, icon: '💧', title: 'الترطيب الواعي', description: 'اشرب الماء ببطء وبنيّة. تخيل جسمك ينظّف ويُطهّر نفسه مع كل رشفة.', duration: 'يومياً' },
            { step: 2, icon: '🧘', title: 'تمرين الحوض', description: 'تمارين قاع الحوض (كيغل) تُقوّي التحكم وتُرسل إشارة أمان للجهاز البولي.', duration: '10 دقائق' },
            { step: 3, icon: '🛡️', title: 'تحديد مصدر التهديد', description: 'ما الذي يجعلك تشعر بأنك "على أهبة الاستعداد" طوال الوقت؟ كن صريحاً.', duration: '15 دقائق' },
            { step: 4, icon: '🕯️', title: 'طقس المساء', description: 'دش دافئ + شاي البابونج + تنفس هادئ قبل النوم. يُرسّخ الهدوء.', duration: '30 دقائق' },
            { step: 5, icon: '✨', title: 'تأكيد شفائي', description: 'أطلق الخوف بسهولة. أنا آمن. الوضع تحت السيطرة.', duration: '5 دقائق' },
        ],
        healingAffirmation: 'أُطلق ما لا أحتاجه بسهولة. أنا بأمان وفي سلام مع الحياة.',
        affirmationEn: 'I release what I no longer need with ease. I am safe.',
        breathingTech: 'box',
        severity: 'moderate',
        prevalence: 6,
        color: '#0D9488',
    },
];

export const getConditionsBySystem = (system: string) =>
    EMOTIONAL_CONDITIONS.filter(c => c.organSystem === system);

export const getConditionById = (id: string) =>
    EMOTIONAL_CONDITIONS.find(c => c.id === id);

export const searchConditions = (query: string) => {
    const q = query.toLowerCase();
    return EMOTIONAL_CONDITIONS.filter(c =>
        c.symptom.includes(query) ||
        c.emotionalConflict.includes(query) ||
        c.targetOrgan.includes(query) ||
        c.triggerEmotions.some(e => e.includes(query))
    );
};
