// lib/clinical-engine/bayesian-hypotheses-hormonal.ts
// Hypotheses Bank — Hormonal, Stress & Psychosomatic Disorders
import type { Hyp } from './bayesian-hypotheses-metabolic';

export const HORMONAL_HYPOTHESES: Hyp[] = [
    { id: 'cortisol_dys', nameAr: 'خلل تنظيم الكورتيزول (HPA)', nameEn: 'HPA Axis Dysregulation', basePrior: 0.15,
      pos: [{s:'إرهاق صباحي',lr:3.5},{s:'طاقة مساء',lr:2.8},{s:'كافيين',lr:2.0},{s:'سكر',lr:1.8},{s:'قلق',lr:1.6},{s:'أرق',lr:2.2},{s:'وزن بطن',lr:2.4},{s:'دوار عند الوقوف',lr:2.6},{s:'حساسية ضوء',lr:2.0},{s:'ملح',lr:1.9},{s:'دوخة عند الوقوف',lr:2.5},{s:'تعب جسدي عاطفي',lr:2.0}],
      neg: [{s:'نشاط صباحي',lr:0.2},{s:'نوم عميق',lr:0.3},{s:'استيقاظ نشط',lr:0.2}],
      pw: ['fatigue','anxiety','sleep','hormonal'],
      test: 'Cortisol AM (8 AM) + DHEA-S + 4-Point Salivary Cortisol + ACTH',
      pearl: 'الكورتيزول المنخفض صباحاً مع القلق = استنزاف HPA وليس زيادة. DHEA-S/Cortisol ratio < ٦ = استنزاف متقدم. CAR غائب = Stage 2 burnout',
      redFlags: ['تصبغ جلد غامق (Addison)','هبوط ضغط شديد','فقدان وزن مع وهن شديد'],
      prevalenceNote: 'شائع جداً في بيئات العمل عالية الضغط والأمهات الجدد وفترة COVID-19 long',
      relatedDx: ['قصور كظرية أديسون','متلازمة كوشينغ','CFS/ME'] },
    { id: 'estrogen_dom', nameAr: 'هيمنة الإستروجين', nameEn: 'Estrogen Dominance', basePrior: 0.18,
      pos: [{s:'دورة مؤلمة',lr:2.8},{s:'ثدي',lr:2.5},{s:'انتفاخ',lr:2.0},{s:'مزاج متقلب',lr:2.3},{s:'وزن ورك',lr:2.1},{s:'أرق قبل الدورة',lr:2.4},{s:'صداع دوري',lr:2.0},{s:'إرهاق قبل الدورة',lr:1.9},{s:'بكاء بلا سبب',lr:2.2},{s:'رغبة شديدة طعام',lr:1.8}],
      neg: [{s:'دورة منتظمة خفيفة',lr:0.4},{s:'لا أعراض PMS',lr:0.3}],
      pw: ['hormonal'],
      test: 'Estradiol + Progesterone (Day 21 of cycle) + SHBG + Testosterone + LH/FSH',
      pearl: 'Estrogen:Progesterone ratio الأهم من القيم المطلقة. DIM (Diindolylmethane) من البروكلي يُحسّن الاستقلاب الإستروجيني',
      redFlags: ['نزيف غير منتظم شديد','كتل ثدي جديدة','ألم حوض مستمر'],
      prevalenceNote: 'يؤثر على ٧٠–٨٠٪ من النساء في مرحلة من حياتهن. الإجهاد المزمن يُسرّع Estrogen Dominance',
      relatedDx: ['PCOS','بطانة رحم هاجرة','أورام ليفية'] },
    { id: 'testosterone_low', nameAr: 'نقص التستوستيرون', nameEn: 'Low Testosterone', basePrior: 0.12,
      pos: [{s:'شهوة منخفضة',lr:3.2},{s:'إرهاق جسدي',lr:2.0},{s:'كتلة عضلية',lr:2.5},{s:'اكتئاب',lr:1.8},{s:'تركيز ضعيف',lr:1.9},{s:'دهون بطن',lr:2.2},{s:'عظام هشة',lr:2.0},{s:'شعر',lr:1.7},{s:'مزاج سيء',lr:1.8}],
      neg: [{s:'رياضة مكثفة',lr:0.5},{s:'طاقة جيدة',lr:0.4}],
      pw: ['fatigue','hormonal'],
      test: 'Total Testosterone (صباحاً) + Free Testosterone + SHBG + LH + FSH + Prolactin',
      pearl: 'Total T طبيعي مع SHBG مرتفع = Free T منخفض. التستوستيرون يبدأ الانخفاض ١٪/سنة بعد ٣٠',
      redFlags: ['انخفاض مفاجئ مع ألم خصية','عقم مع نقص T مثبت'],
      prevalenceNote: 'الإجهاد المزمن + الوزن الزائد + قلة النوم يُسرّعون انخفاض التستوستيرون عند الرجال',
      relatedDx: ['قصور نخامية','أورام خصية','متلازمة كلاينفلتر'] },
    { id: 'pcos', nameAr: 'تكيس المبايض (PCOS)', nameEn: 'PCOS', basePrior: 0.10,
      pos: [{s:'دورة غير منتظمة',lr:3.5},{s:'شعر وجه',lr:3.0},{s:'حب شباب',lr:2.2},{s:'وزن',lr:2.0},{s:'تساقط شعر أمامي',lr:2.5},{s:'بطن',lr:1.9},{s:'سكر',lr:2.2},{s:'دورة غائبة',lr:3.0},{s:'خصوبة',lr:2.8}],
      neg: [{s:'دورة منتظمة جداً',lr:0.2},{s:'بدون شعر زائد',lr:0.5}],
      pw: ['hormonal'],
      test: 'LH/FSH ratio + Total Testosterone + DHEA-S + Prolactin + Ultrasound مبايض + HOMA-IR',
      pearl: 'LH/FSH > ٢:١ + Androgen زائد + Polycystic Ovaries = Rotterdam Criteria. ٧٠٪ من PCOS لديهن مقاومة أنسولين',
      redFlags: ['حمل مع PCOS غير مُعالج (خطر سكري حمل)','نزيف رحمي غير منتظم'],
      prevalenceNote: 'أكثر اضطراب هرموني عند النساء في سن الإنجاب: ١٠–١٥٪',
      relatedDx: ['مقاومة أنسولين','Hypothyroidism','فرط برولاكتين'] },
    { id: 'food_sensitivity', nameAr: 'حساسية غذائية خفية', nameEn: 'Food Sensitivity (IgG)', basePrior: 0.30,
      pos: [{s:'انتفاخ',lr:2.5},{s:'بعد الأكل',lr:3.0},{s:'إسهال',lr:2.2},{s:'إمساك',lr:1.8},{s:'صداع',lr:1.6},{s:'جلد',lr:1.9},{s:'تعب بعد أكل',lr:2.8},{s:'غازات',lr:2.4},{s:'حكة',lr:2.0},{s:'احتقان أنف',lr:1.7},{s:'أكزيما',lr:2.3},{s:'إرهاق بعد وجبة',lr:2.6},{s:'غثيان خفيف',lr:1.8}],
      neg: [{s:'هضم ممتاز دائماً',lr:0.2},{s:'لا أعراض بعد الأكل',lr:0.3}],
      pw: ['digestion','fatigue','headache','immune'],
      test: 'حمية إقصائية ٦ أسابيع (الطيبات) ← إعادة إدخال عنصر/٣ أيام',
      pearl: 'IgG food panels تجارية غير موثوقة علمياً — الحمية الإقصائية + إعادة الإدخال هي المعيار الذهبي. ابدأ بحذف القمح والألبان',
      redFlags: ['صعوبة تنفس بعد الأكل (حساسية IgE — طارئ)','تورم الوجه واللسان'],
      prevalenceNote: 'القمح والألبان = ٧٠٪ من حالات الحساسية الغذائية في المنطقة العربية',
      relatedDx: ['سيلياك','SIBO','عدم تحمل اللاكتوز','IBS'] },
    { id: 'adrenal_fatigue', nameAr: 'إرهاق الكظرية (Stage 3)', nameEn: 'Adrenal Exhaustion', basePrior: 0.10,
      pos: [{s:'منهك تماماً',lr:4.0},{s:'لا طاقة أبداً',lr:3.8},{s:'انهيار',lr:3.5},{s:'مستنزف',lr:3.2},{s:'لا أستطيع',lr:3.0},{s:'نوم لا يُريح',lr:2.8},{s:'كل شيء صعب',lr:2.5},{s:'ملح',lr:2.0},{s:'دوار',lr:1.9},{s:'حساسية ضوء',lr:2.2}],
      neg: [{s:'طاقة جيدة',lr:0.1},{s:'نشاط صباحي',lr:0.2}],
      pw: ['fatigue'],
      test: '4-Point Salivary Cortisol + DHEA-S + Pregnenolone + ACTH + Cortisol AM',
      pearl: 'مصطلح "Adrenal Fatigue" طبي وظيفي — لا يعني قصور الكظرية الحقيقي (Addison). Flat Cortisol Curve = النمط المميز',
      redFlags: ['هبوط ضغط شديد عند الوقوف (Orthostatic Hypotension)','تصبغ غير طبيعي'],
      prevalenceNote: 'COVID Long Haul + Burnout الحديث رفعا الانتشار بشكل كبير',
      relatedDx: ['CFS/ME','Fibromyalgia','قصور الكظرية الحقيقي'] },
];
